//
// Created by Quinn on 10/3/2025.
// AI WAS USED TO MAKE THE CODE IN THIS FILE
// The code in this file was generated by Gemini AI so that I could have a formatted account printer
// The reason for doing this was because I wanted to get all of the accounts printed out, and was not able to figure out how to get them properly spaced
//

#ifndef TESTING_PIPELINEPRINTING_H
#define TESTING_PIPELINEPRINTING_H

#include <vector>
#include <string>

using FormattedTable = std::vector<std::vector<std::string>>;

struct Account {
    int option;
    std::string ID;
    std::string type;
    std::string holder;
    double balance;
};



class pipelineprinting {
public:
    static void printTable(const FormattedTable& table);

    static void printCentered(const std::string& text, int width);

    static FormattedTable formatCustomData(const std::vector<Account>& accounts);
};


#endif //TESTING_PIPELINEPRINTING_H